### PR TITLE
small fixes...

### LINKED ISSUE #12: Errors should not leak internals
Currently, all errors happening in the API are returned as they appear. This can leak information which we don’t want to have visible from the outside. Therefore, all errors should return a generic error object with helpful error messages for the client but without leaking any internals, e.g.:

```json
{
  "code": 500,
  "message": "Internal Server Error // or whatever happened"
}
```

### PR DESCRIPTION
**Pull request by ca057**
This fixes #12

### CODE REVIEW

File: interface/rest/error_handler.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package rest
+
+import (
+	"net/http"
+
+	rest "github.com/der-nackte-halloumi/api/interface/rest/models"
+)
+
+type errorHandler struct{}
```
Comment (joshuaslate) [inline interface/rest/error_handler.go:9]: Would you want to put a logger or something here? Maybe you're handling that at a higher level-- just checking.

Comment (ca057) [reply interface/rest/error_handler.go:9]: Don’t have a logger yet, but thanks for the hint! That basically means, I would inject a logger here to log the errors in one central place?

Comment (joshuaslate) [reply interface/rest/error_handler.go:9]: Yeah, just so you can track/find 404s.

**Review by joshuaslate — APPROVED** [review]
